### PR TITLE
Chorobrewer

### PR DESCRIPTION
**Pull request by sjsrey**
- notebook example
- streamline map
- interactions between k, cmap, and ctype

### CODE REVIEW

**Comment by renanxcortes** [comment]
Nice, this is getting realcool. Could you add an `%matplotlib inline` in the beginning of the notebook?
Also, just a question... how could I install the mapclassify version of the chorobrewer branch without conflicting the modules? I'm kind of getting some error `ImportError: cannot import name 'color'` from mapclassify. Is there a convenient way to prevent that on my side?

**Comment by sjsrey** [comment]
> Nice, this is getting really cool. Could you add an `%matplotlib inline` in the beginning of the notebook?

will do.

> Also, just a question... how could I install the mapclassify version of the chorobrewer branch without conflicting the modules? I'm kind of getting some error `ImportError: cannot import name 'color'` from mapclassify. Is there a convenient way to prevent that on my side?

in the toplevel of mapclassify what i do is 

1. create a conda environment
2. start that environment
3. python setup.py develop

**Comment by sjsrey** [comment]
> This is cool, in addition, I think adding a `%matplotlib inline` at the beginning of the notebook.

i was going to add it, but things work fine on my install without the cell magic so I'm wondering if we really need it?

**Comment by renanxcortes** [comment]
> > This is cool, in addition, I think adding a `%matplotlib inline` at the beginning of the notebook.
> 
> i was going to add it, but things work fine on my install without the cell magic so I'm wondering if we really need it?

hm... interesting, if that's the case, no problem!

**Comment by knaaptime** [comment]
it's always hit or miss for me. Most of the time I dont need it


...until that random time i fire up a notebook and figures dont show  🤷‍♂️

**Pull request merged**
