### PR TITLE
Add monthly downloads badge to README

### PR DESCRIPTION
**Pull request by ayushjain01**
Just a suggestion. I've been working on developing a badge system for Python packages to display statistics like monthly downloads. You can check it out at - https://piptrends.com/package/mapclassify.

Our goal at Pip Trends is to create a learning forum where developers can access everything they need to get started with Python and Python packages.

The badge links to the mapclassify page on Pip Trends, showcasing various stats and documentation. We plan to add simple getting-started articles and more to this page soon, and contributions are welcome. If necessary, this link can be removed. This PR is just to share the badge we have created.

### CODE REVIEW

**Comment by martinfleis** [comment]
Thanks! Though I am not sure I am in favour.

If we want a badge showing number of downloads I would rather suggest using [shields.io option](https://shields.io/badges/py-pi-downloads) as we do with other badges. That also ensures it looks the same. And the link shall probably go to PyPI.

This PR feels more like a way of getting piptrends into the wild rather than an improvement of our Readme.

**Comment by ayushjain01** [comment]
Understandable, like i mentioned earlier, this is just a suggestion and we just want to share something we built. Also about the link to piptrends.com, like I mentioned can be removed if needed.
The goal is to only share something we have built and nothing else. 

About using shields.io, I believe their counts are a little inconsistent compared to the actual counts. (The download counts differ by a margin of ~6k) 

PyPI - Downloads
[mapclassify Downloads Last Month](https://piptrends.com/package/mapclassify)

Our count matches the following query:

```SQL
SELECT COUNT(*) AS num_downloads
FROM `bigquery-public-data.pypi.file_downloads`
WHERE file.project = 'sqlalchemy'
  -- Only query the last 30 days of history
  AND DATE(timestamp)
    BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 30 DAY)
    AND CURRENT_DATE()
```
Not quite sure why the shield.io badge has inconsistent counts, but it's the same across all packages. You can refer to the [Python Packaging User Guide](https://packaging.python.org/en/latest/guides/analyzing-pypi-package-downloads/#counting-package-downloads) for more information.

**Comment by ixmatus** [comment]
@martinfleis a colleague of this person tried to open this exact PR against a project I'm the maintainer for as well (https://github.com/ixmatus/inflector/pull/16). This is a promotional campaign and they (or colleagues) appear to be doing it on reddit too, I think this is suspicious activity. They are creating an external dependency on a web property that (as far as I can tell) is not officially blessed by pypi. I recommend rejecting this PR.

Users can get package statistics from `libraries.io` which is linked to directly by pypi itself.

**Comment by martinfleis** [comment]
@ixmatus Well said.

**Comment by ayushjain01** [comment]
Thank you for your feedback and concerns. I'd like to clarify that this is not a promotional campaign. As stated in the PR description, our intention is simply to share a tool we have developed, which we believe could be beneficial to the community.

Our badge system offers highly accurate statistics, which is why we wanted to make it available. If the link to the pip trends page is a concern, we are more than willing to remove it.

We respect your decision if you prefer not to add more badges to your README. Our primary goal is to address any misunderstandings and assure you that this is a genuine effort to contribute to the open-source community by sharing our work on GitHub.

Thank you for considering our contribution.

**Pull request closed without merging**
