### PR TITLE
Pooled

### PR DESCRIPTION
**Pull request by sjsrey**
Adds pooled classification.

Also extends MaximumBreaks to handle cases where insufficient unique differences occur.

TODO

- [x] Tests

### CODE REVIEW

**Comment by sjsrey** [comment]
Addressing #51

**Comment by sjsrey** [comment]
> really small typo in cell 4 of the notebook (stray parentheses) but this looks great.
> 
> to extend this in the future, instead of "proper" pooling, it could be nice to include an option to define one of the columns that's used to create the breaks, then the other columns are assigned to those breaks

Something like a "pinned" argument that defines which column to define the breaks on, and then other columns are classified to these bins?

**Comment by knaaptime** [comment]
yeah thats exactly what i was thinking. For if you want to see the 1990-2010 time series, but expressed in the 2010 quantiles for each period

**Comment by sjsrey** [comment]
> yeah thats exactly what i was thinking. For if you want to see the 1990-2010 time series, but expressed in the 2010 quantiles for each period

Could do that with the current PR implementation with something like:

```
res = mc.Pooled(Y, classifier='UserDefined', bins=mc.Quantiles(Y[:,-1]).bins)
```

**Pull request merged**
