### PR TITLE
Add type signatures to jenksy

### PR DESCRIPTION
**Pull request by cheginit**
Per the discussion in #118, this PR does the following:

- Add numba type signatures to `_fisher_jenks_means`
- Remove `sort` argument from `_fisher_jenks_means` since it's not being passed from the class function and is always `True`.
- Add a new `extra_req` to `setup.py` for installing `numba` as `speedups`.
- Add `__pycach__` to `.gitignore` since `numba` compiles the function and keep in the cache folder.
- Warn the user if `numba` is not installed the (slow) pure Python code is used.

### CODE REVIEW

**Comment by cheginit** [comment]
Two of the `greedy` tests fail and since they are not related to this PR I didn't attempt to address them.

**Comment by martinfleis** [comment]
(sorry for closing and reopening, I wanted to make sure CI kicks in)

**Comment by cheginit** [comment]
Sure. No problem! The tests in the CI are passing. However, I used Python 3.10 and latest versions of the dependencies to run `pytest` on my machine and two of the `greedy` tests failed. Looking at the source code, the problem seems to be with the latest version of `networkx`. The assertions fail.

**Comment by cheginit** [comment]
I used `tox-conda` with the following config and all tests pass. I am not sure why three of the CI's were stuck for 3 hours.

```ini
[tox]
envlist =
    {py36,py37,py38}-{speedup,slow}

[testenv]
conda_deps=
    pytest
    pytest-cov
    codecov
    geopandas
    libpysal
    networkx
    palettable
    speedup: numba
commands=
    pytest {posargs}
```

**Review by martinfleis — APPROVED** [review]
The PR looks okay to me! Thanks!

> However, I used Python 3.10 and latest versions of the dependencies to run pytest on my machine and two of the greedy tests failed.

You can ignore that. I'll make a PR slimming down our CI matrix and including python 3.10 and look into this.

> I am not sure why three of the CI's were stuck for 3 hours.

don't know either

**Comment by martinfleis** [comment]
> two of the greedy tests failed.

See https://github.com/networkx/networkx/issues/3993

**Comment by cheginit** [comment]
Oh. So the issue has been there for a while.

Sounds good! Let me know if this PR needs any other changes.

**Comment by cheginit** [comment]
It's been a while since I opened this PR, do I need to change anything in this PR?

**Pull request merged**
