### PR TITLE
infrastructure modernization, etc.

### LINKED ISSUE #190: modernize infrastructure (2023/09)
*  [x] swap `versioneer` for `setuptool_scm` – [9764687](https://github.com/pysal/mapclassify/pull/193/commits/97646872ff8db39f79a7fac8532a79b35ea9db87)
* [x] migrate to `pyproject.toml` – [d55f7de](https://github.com/pysal/mapclassify/pull/193/commits/d55f7deac08321f446c4a739e3bdccfd3d1983f2)
* [x] update `pre-commit-config` – [c2fa127](https://github.com/pysal/mapclassify/pull/193/commits/c2fa12729b9f0f2f945eb4625b8b36f567de5338)
* [x] drop 3.8 testing (thoughts @martinfleis? maybe too soon?) – [15c6118](https://github.com/pysal/mapclassify/pull/193/commits/15c61189b45f2ba08375b6d9ed4f8d4ec2a333be)
* [x] add 3.11 testing with `numba` – [83ebfa6](https://github.com/pysal/mapclassify/pull/193/commits/83ebfa614a2890a67add2066a2c58bd3b736bf9e)
* [x] review & update workflows as needed – [15c6118](https://github.com/pysal/mapclassify/pull/193/commits/15c61189b45f2ba08375b6d9ed4f8d4ec2a333be)
* [x] purge superfluous files – [d55f7de](https://github.com/pysal/mapclassify/pull/193/commits/d55f7deac08321f446c4a739e3bdccfd3d1983f2)

### LINKED ISSUE #192: minimal requirements CI env
Add a truly minimal requirements test environment for CI.

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR:
* resolves #190 
* resolves #192

### CODE REVIEW

**Comment by jGaboardi** [comment]
@martinfleis Looks like all tests are passing. After your review, and appropriate changes, should I do a lint commit for this PR or do the `ruff`ing in another PR?

**Review by sjsrey — APPROVED** [review]
LGTM 
Thanks!

**Comment by martinfleis** [comment]
This will also need an update of the release workflow. We need to install mapclassify there to get a version and avoid a direct call of setup.py.

I'd do linting as a follow-up

**Comment by jGaboardi** [comment]
> This will also need an update of the release workflow. We need to install mapclassify there to get a version and avoid a direct call of setup.py.

good catch, done.

**Review by martinfleis — COMMENTED** [review]
Not entirely done. 

`build_docs` needs to pip install the package (https://github.com/pysal/esda/blob/3f5ce84648645d87582f40dd4ae68f7bf592c022/.github/workflows/build_docs.yml#L38-L39). Otherwise it won't pull the version.

**Comment by jGaboardi** [comment]
dang it... OK, now I think done.

**Review by martinfleis — APPROVED** [review]

**Pull request merged**
